DELIMITER //
USE chetcom //
DROP TRIGGER UpdateStudentCount;
CREATE TRIGGER UpdateStudentCount
    AFTER DELETE
    ON STUDENT
    FOR EACH ROW
BEGIN
    
END //
DELIMITER ;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM STUDENT WHERE CCCD_number = 025303001515;